project:
  type: website
  output-dir: docs

book:
  title: "2406_IntroR_material"
  author: "Norah Jones"
  date: "16/6/2024"
  page-navigation: true
  downloads: pdf
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  
  navbar: 
    search: true

bibliography: references.bib

format:
  html:
    theme: flatly
    navigation:
      sidebar:
        sticky: true
    code-fold: true
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
  pdf:
    documentclass: scrreprt

editor: visual

