project:
  type: website
  output-dir: docs

execute:
  #echo: false
  warning: false

book:
  title: "¿Datos para qué? Intro al mundo de datos con R"
  author: "Tomás Bustos"
  date: "19/09/2024"

website:
  title: "¿Datos para qué? Intro al mundo de datos con R"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Tomás Bustos | Ciudad de Buenos Aires | agosto 2024"
  navbar:
    background: primary
    foreground: secondary
    search: true
    left: 
      - intro.qmd
      - procesamiento.qmd
      - analisis.qmd
      - viz.qmd
      
  sidebar:
    title: "Capítulos"
    subtitle: "Capítulos sub"
    style: "docked"
    tools:
      - icon: github
        menu: 
          - text: "Código fuente"
            href: https://github.com/bustosthl/intro_R
      - icon: linkedin
        href: https://www.linkedin.com/in/tomasbustos/
    contents: 
      - text: "Presentación"
        href: index.qmd
      - text: "1. Piletazo"
        href: intro.qmd
      - text: "2. Procesamiento"
        href: procesamiento.qmd
      - text: "3. Análisis"
        href: analisis.qmd
      - text: "4. Visualización"
        href: viz.qmd
          
      
format:
  html:
    theme: simplex #flatly
    toc: true
    toc-title: "Apartados"
  pdf:
    documentclass: scrreprt

editor: visual

