project:
  type: website
  output-dir: docs

execute:
  #echo: false
  warning: false

book:
  title: "¿Datos para qué? Intro al mundo de datos con R"
  author: "Tomás Bustos"
  date: "19/09/2024"

website:
  title: "¿Datos para qué? Intro al mundo de datos con R"
  navbar:
    search: true
    left: 
      - index.qmd
      - intro.qmd
      - procesamiento.qmd
      - analisis.qmd
      - viz.qmd
      #- summary.qmd
    #right:
     # - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: simplex #flatly
    toc: true
    toc-title: "Apartados"
  pdf:
    documentclass: scrreprt

editor: visual

