# Presentación del curso {.unnumbered}

El objetivo de los siguientes párrafos es dar una cálida y armoniosa bienvenida al mundo de datos para personas de la carrera de Sociología de la UBA, pero extensible a distintas carreras de Ciencias Sociales a lo largo y ancho de la República Argentina.

```{r}
#| echo: false
library(tidyverse)
```

## ¿Por qué "datos"?

Se popularizó en los últimos años el brumoso término de *Big Data*, un espacio [*sexy*](https://www.infobae.com/tecno/2017/05/09/cientifico-de-datos-por-que-es-la-profesion-mas-sexy-del-siglo-xxi/) y confuso en donde se reunieron distintas técnicas, disciplinas y profesiones que lograban incorporar algún elemento novedoso al viejo arte trabajar con datos.

¿Qué es lo realmente interesante? Las tres famosas "V" bocetan un nuevo contexto de circulación de los datos: en grandes **volúmenes**, en tipos y formatos **variados** y con una mayor **velocidad** de intercambio y capacidad de cómputo. Ahora bien, como toda persona que quiera dedicarse a las Ciencias Sociales sabe (¡o debe saber!), poder recolectar, comprender, administrar y analizar datos para construir información es una parte fundamental del proceso de investigación. Al final, el enfoque de este espacio enfoque será cómo navegar las nuevas tempestades para ejercer el oficio que nos interpeló en un primer momento.

Sesgo de ciencia de datos \###

## ¿Por qué R?

`R` es un lenguaje de programación enfocado en análisis y visualización de datos. Nos agrada particularmente por ser un producto de software libre y código abierto: puede ser usado, modificado y citado sin pagar licencias de ningún tipo. Además presenta alrededor del globo -y en Argentina en particular- una gran comunidad de usuarios que crean formas específicas de aplicación de este lenguaje que nos facilitará su uso en Ciencias Sociales. Ya sea por facilitar el acceso a ciertas fuentes de información, por sintetizar procesos complejos en funciones simples de ejecutar o tan sólo por tener espacios donde realizar consultas y recibir apoyo.

Un detalle no menor: `R`, como toda herramienta, es sólo la manera (a nuestro entender) más simple de acceder *al mundo de datos*. La idea es que funcione como puerta de entrada al entendimiento de las lógicas de la programación y el manejo de los distintos objetos que vamos a utilizar aquí.

R y Rstudio: \###

## Objetivo

Se busca realizar una introducción general al uso del lenguaje `R` a través de la interfaz `Rstudio`, priorizando los paquetes incluídos en la colección `Tidyverse` y con especial foco en el proceso de extracción, limpieza, análisis y visualización de datos.

errores \###

## Organización

El curso se estructura en XXX encuentros virtuales sincrónicos de XX horas cada uno a realizarse por la plataforma XXXX.

## Agradecimientos

lorem ipsus
